# traefik.yml
api:
  dashboard: true
  insecure: true  # Only for development

entryPoints:
  web:
    address: ":80"
    # Increase timeouts
    transport:
      respondingTimeouts:
        readTimeout: 60s
        writeTimeout: 60s
        idleTimeout: 60s

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
    watch: true