# Project docker-compose.yml (for your Next.js app)
# version: '3.8'

services:
  nextjs:
    image: school-management-system-nextjs-atl:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3005}:3000"
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${DOMAIN}
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.dorkms-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.dorkms-http.entrypoints=http
      - traefik.http.routers.dorkms-http.middlewares=https-redirect
      - traefik.http.routers.dorkms-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.dorkms-https.entrypoints=https
      - traefik.http.routers.dorkms-https.tls=true
      - traefik.http.routers.dorkms-https.tls.certresolver=le
      - traefik.http.routers.dorkms-https.service=dorkms-service
      - traefik.http.services.dorkms-service.loadbalancer.server.port=3000
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - web
      - traefik-public
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./backups:/app/backups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      # start_period: 30s
    networks:
      - traefik-public
    command:
      - "postgres"
      - "-c"
      - "ssl=off"

volumes:
  postgres-data:
    driver: local

networks:
  web:
    external: true
  # app-network:
  #   driver: bridge
  traefik-public:
    external: true